# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.destroy_all
Species.destroy_all

birds= Category.create! ({customizable: false, name: "birds"})
mammals= Category.create! ({customizable: false, name: "mammals"})
fish= Category.create! ({customizable: false, name: "fish"})
reptiles= Category.create! ({customizable: false, name: "reptiles"})
amphibians= Category.create! ({customizable: false, name: "amphibians"})
insects= Category.create! ({customizable: false, name: "insects"})

species= Species.create!([
    {common_name:"Reticulated flatwoods salamander ", scientific_name:"Ambystoma bishopi", status:"Endangered ", threat:"The principal threat is habitat destruction as a result of agriculture, silviculture, and residential and commercial development.", img_url:"http://www.caudata.org/cc/images/species/Ambystoma/A_bishopi1BARTLETT.jpg", category: amphibians},
    {common_name:"Frosted Flatwoods salamander", scientific_name:"Ambystoma cingulatum", status:"Endangered", threat:"Potential threats include conversion of pine flatwoods habitat for agriculture, silviculture, or commercial/residential development; drainage or enlargement (with subsequent introduction of predatory fishes) of breeding ponds; habitat alteration resulting from suppression of fire; mortality and collecting losses associated with crayfish harvest; and highway mortality during migration.", img_url:"http://calphotos.berkeley.edu/imgs/512x768/1111_1111/1111/4649.jpeg", category: amphibians},
    {common_name:"Shenandoah salamander", scientific_name:"Plethodon shenandoah", status:"Endangered ", threat:"Infestation by non-native insects/disease; restricted range of habitat", img_url:"http://www.virginiaherpetologicalsociety.com/amphibians/salamanders/shenandoah-salamander/Shenandoah%20Salamander%20(Plethodon%20shenandoah)0002.JPG", category: amphibians},
    {common_name:"Sand skink", scientific_name:"Neoseps reynoldsi", status:"Threatened", threat:"This species is threatened by habitat destruction for commercial and residential development, agricultural (citrus) development, and phosphate mining. Conversion of habitat to citrus production is the primary threat. Habitat degradation due to fire exclusion is another threat.", img_url:"https://ecos.fws.gov/docs/species_images/doc5037.jpg", category: amphibians},
    {common_name:"Dusky Gopher Frog", scientific_name:"Rana sevosa", status:"Endangered", threat:"Major threats include population isolation (inbreeding and susceptibility to catastrophic events), urbanization, two diseases, and apparent lack of a nearby suitable habitat. The range has been significantly reduced as a result of habitat destruction, fragmentation, and modification.", img_url:"https://ecos.fws.gov/docs/species_images/doc1756.jpg", category: amphibians},
    {common_name:"Red Knot", scientific_name:"Calidris canutus rufa", status:"Threatened", threat:"The species is vulnerable to extensive land reclamation projects that encroach upon important habitat across its range. Loss of intertidal stopover habitats due to reclamation activities in the Yellow Sea region of the East Asian-Australasian Flyway is thought to be driving declines in shorebird populations. These losses are attributed to urban, industrial and agricultural expansion within the region.",  img_url:"https://ecos.fws.gov/docs/species_images/doc3682.jpg", category: birds},
    {common_name:"Bachman's Warbler", scientific_name:"Vermivora bachmanii", status:"Critically Endangered", threat:"The drainage of river-bottom swamplands, and the near-total clearance of canebrakes in the USA, combined with the conversion of much of Cuba to sugarcane plantation", img_url:"https://identify.whatbird.com/img/4/63878/image.aspx", category: birds},
    {common_name:"Roseate tern", scientific_name:"Sterna dougallii dougallii", status:"Threatened", threat:"Predation by rats, ferrets, red foxes and Peregrine Falcon (Falco peregrinus) occurs locally, and can have significant effects, including complete breeding failure at some Azores colonies. Natural predators can often take a great toll on localised colonies, particularly when terns are disturbed from the nest by other birds and humans.", img_url:"https://ecos.fws.gov/docs/species_images/doc4948.jpg", category: birds},
    {common_name:"Red-cockaded Woodpecker", scientific_name:"Picoides borealis", status:"threatened", threat:"Because of its biology and dependence on old-growth forest, this species is said to be uniquely susceptible to rapid declines under inappropriate management regimes. The long-term clearance and economic management of habitat has reduced the viability of all populations.", img_url:"https://ecos.fws.gov/docs/species_images/doc3700.jpg", category: birds},
    {common_name:"Piping Plover", scientific_name:"Charadrius melodus", status:"Threatened", threat:"Drought, inappropriate water and beach management, gas/oil industry dredging operations, development, shoreline stabilisation and beach disturbance (including cat and dog predation, and possibly that from native avian species and ghost crabs) are key threats. Coastal flooding driven by climate change has been noted to cause reduced reproductive success in Virginia, and its importance is likely to increase.", img_url:"https://ecos.fws.gov/docs/species_images/doc3770.jpg", category: birds},
    {common_name:"Kirtland's warbler", scientific_name:"Setophaga kirtlandii", status:"Threatened ", threat:"Parasitism by brown-headed Cowbird Molothrus ater is a threat in breeding areas.  Wintering threats destroying fruit and habitat.", img_url:"https://upload.wikimedia.org/wikipedia/commons/d/d1/Dendroica_kirtlandii_-Michigan%2C_USA_-male-8_%287%29.jpg", category: birds},
    {common_name:"Wood Stork", scientific_name:"Mycteria americana", status:"Threatened", threat:"Habitat loss", img_url:"https://ecos.fws.gov/docs/species_images/doc5013.jpg", category: birds},
    {common_name:"Audubon's crested caracara", scientific_name:"Polyborus plancus audubonii", status:"Threatened", threat:"The main cause of habitat loss includes modification for urban development and agriculture.", img_url:"https://ecos.fws.gov/docs/species_images/doc5038.jpg", category: birds},
    {common_name:"Florida scrub-jay", scientific_name:"Aphelocoma coerulescens", status:"Vulnerable", threat:"Fire suppression in remaining habitat has been identified as a major continuing threat because it causes scrub to overgrow and pine density to increase, rendering habitat unsuitable. Declines on lands specifically protected for the species are largely the result of reduced habitat quality, caused by disrupted fire regimes.", img_url:"https://ecos.fws.gov/docs/species_images/doc4851.jpg", category: birds},
    {common_name:"Cape Sable Seaside sparrow", scientific_name:"Ammodramus maritimus mirabilis", status:"Endangered", threat:"Predation and habitat loss", img_url:"https://ecos.fws.gov/docs/species_images/doc5035.jpg", category: birds},
    {common_name:"Florida Grasshopper sparrow", scientific_name:"Ammodramus savannarum floridanus", status:"Endangered", threat:"Predation and habitat loss", img_url:"https://ecos.fws.gov/docs/species_images/doc5034.jpg", category: birds},
    {common_name:"Yellow-Shouldered Blackbird", scientific_name:"Agelaius xanthomus", status:"Endangered", threat:"Habitat loss", img_url:"https://ecos.fws.gov/docs/species_images/doc3676.jpg", category: birds},
    {common_name:"Least Tern", scientific_name:"Sterna antillarum", status:"Endangered", threat:"Habitat loss", img_url:"http://avesphoto.com/website/pictures/TRNLST-1.jpg", category: birds},
    {common_name:"Mississippi Sandhill crane", scientific_name:"Grus canadensis pulla", status:"Endangered", threat:"Habitat loss", img_url:"https://ecos.fws.gov/docs/species_images/doc4896.jpg", category: birds},
    {common_name:"Atlantic Salmon", scientific_name:"Salmo salar", status:"Endangered", threat:"Human consumption", img_url:"https://ecos.fws.gov/docs/species_images/doc4936.jpg", category: fish},
    {common_name:"Big Sandy crayfish ", scientific_name:"Cambarus callainus", status:"Threatened ", threat:"Extractive industry, logging and road construction. This has caused fragmentation and degradation of habitat that has historically been used by this species.", img_url:"https://upload.wikimedia.org/wikipedia/commons/2/27/Chattooga_River_Crayfish_%2814174938652%29.jpg", category: fish},
    {common_name:"Duskytail darter", scientific_name:"Etheostoma percnurum", status:"Endangered ", threat:"Impoundment of waterways, increased silt, logging, coal mining and disease", img_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Etheostoma_percnurum.jpg/1024px-Etheostoma_percnurum.jpg", category: fish},
    {common_name:"Maryland Darter", scientific_name:"Etheostoma sellare", status:"Extinct", threat:"This species probably is extinct. It was most recently confirmed from the last known location (Deer Creek) in 1986", img_url:"Darter fish with a halo swimming in the clouds", category: fish},
    {common_name:"Shortnose Sturgeon", scientific_name:"Acipenser brevirostrum", status:"Endangered", threat:"Although some shortnose sturgeon may be harvested incidental to Atlantic sturgeon in Canada, there are no legal fisheries or by-catch allowances in U.S. waters. Principal threats to the survival of this species are blockage of up- and downstream migrations at dams, habitat loss or degradation due to dams and dam operations, river channel dredging, and pollution.", img_url:"https://ecos.fws.gov/docs/species_images/doc3737.jpg", category: fish},
    {common_name:"Spotfin chub", scientific_name:"Cyprinella monacha", status:"Vunerable ", threat:"Habitat loss, sedimentation, and dams", img_url:"https://static.wixstatic.com/media/6f2f2b_cc97e5c302fc44d78d83128b50f1d4bb.jpg_srz_541_419_85_22_0.50_1.20_0.00_jpg_srz", category: fish},
    {common_name:"Roanoke logperch", scientific_name:"Percina rex", status:"Threatened", threat:"Decline over the long term likely resulted from reservoir creation and widespread siltation caused by land development and agricultural activities. The upper Roanoke River population is threatened by ongoing urbanization, industrial development, water supply and flood control projects, and agricultural runoff in the upper basin; known threats continue to exist in the Roanoke River drainage. Smith River population is threatened by operation of Philpott Dam and by continued siltation from upstream agriculture. Threats (mainly siltation) in the Nottoway River recently have decreased. Other populations are subject to siltation from agricultural and other human activities and to potential chemical spills.", img_url:"https://upload.wikimedia.org/wikipedia/commons/1/1a/Percina_rex.jpg", category: fish},
    {common_name:"Smalltooth Sawfish", scientific_name:"Pristis pectinata", status:"Critically Endangered", threat:"The principal threats to Smalltooth Sawfish are from fishing; it was formerly targeted, but is now mostly taken incidentally in broad-spectrum fisheries. The long toothed rostrum of sawfish makes them extremely vulnerable to entanglement in any sort of net gear, gillnetting and trawling in particular.", img_url:"https://ecos.fws.gov/docs/species_images/doc1736.jpg", category: fish},
    {common_name:"Blue Shiner", scientific_name:"Cyprinella caerulea", status:"Threatened", threat:"Declines have been caused by water pollution, siltation, and construction of reservoirs for hydropower, navigation, and flood control. These degraded/destroyed the habitat and fragmented the populations. Current concerns include siltation and excessive nutrient inputs deriving from runoff from small-scale agriculture, grazing, and urbanization.", img_url:"http://www.outdooralabama.com/sites/default/files//fishing/images/Shinerblue400A.jpg", category: fish},
    {common_name:"Spotfin Chub", scientific_name:"Erimonax monachus", status:"Threatened", threat:"Range may have been more continuous before extensive deforestation and impoundment. Causes of decline include siltation, coal sedimentation, pollution, inundation by reservoir development, releases of cold water from reservoirs, stream channelization, and interspecific competition; some of these factors affect extant populations. Collecting may significantly reduce local subpopulations.", img_url:"https://cff2.earth.com/uploads/2017/01/03143939/Erimonax-monachus.jpg", category: fish},
    {common_name:"Cape Fear Shiner", scientific_name:"Notropis mekistocholas", status:"Endangered", threat:"Threats include deterioration of water quality due to toxic chemical pollution, changes in stream flow, channel modification, siltation, and impoundments (North Carolina Natural Heritage Program).
    ", img_url:"https://static.wixstatic.com/media/6f2f2b_6616514e0ead4e6ba7a66456da14769b.jpg_srz_557_369_85_22_0.50_1.20_0.00_jpg_srz", category: fish},
    {common_name:"Atlantic Sturgeon", scientific_name:"Acipenser oxyrinchus", status:"Endangered", threat:"Atlantic sturgeon were an important item of commerce to early American and Canadian colonists and large quantities of meat, roe, oil and isinglass were exported to Europe late 17th and 18th centuries. As flesh and roe (caviar) gained popularity in North American, the species was heavily exploited, particularly during several decades of the late nineteenth century.", img_url:"https://upload.wikimedia.org/wikipedia/commons/8/87/Acipenser_oxyrinchus_BM.jpg", category: fish},
    {common_name:"Pallid Sturgeon", scientific_name:"Scaphirhynchus albus", status:"Endangered", threat:"Habitat modification, including the construction of six main stem dams on the Missouri River and extensive channelisation in the lower Missouri and Mississippi Rivers, is the primary factor affecting the continued existence of this species.", img_url:"http://www.tnaqua.org/images/uploads/our_animals/Pallid-sturgeon_1200x490.jpg", category: fish},
    {common_name:"Scioto Madtom", scientific_name:"Noturus trautmani", status:"Endangered", threat:"Habitat loss", img_url:"http://www.fishbase.org/images/species/Nomiu_u0.jpg", category: fish},
    {common_name:"Blackside dace", scientific_name:"Phoxinus cumberlandensis", status:"Threatened", threat:"Threatened status is due primarily to impacts of siltation from coal mining, silviculture, agriculture, and road construction, and impacts of unregulated acid mine drainage and impoundments; these factors still constitute a threat.", img_url:"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQb8vRAoz1ZLrdtgsl1KnjbQX45x45KbS2yotw5q0w5oI4zhaY_", category: fish},
    {common_name:"Yellowfin madtom", scientific_name:"Noturus flavipinnis", status:"Vulnerable", threat:"Impoundments, chemical spills, mining, dredging, and pollution.", img_url:"https://www.floridamuseum.ufl.edu/catfish/ictaluridae/flavipinnis2.jpg", category: fish},
    {common_name:"Waccamaw silverside", scientific_name:"Menidia extensa", status:"Threatened", threat:"Threatened by the usual problems associated with limited distribution and by increased nutrient loading.", img_url:"http://www.fishbase.org/images/species/Mepen_u0.jpg", category: fish},
    {common_name:"Okaloosa Darter", scientific_name:"Etheostoma okaloosae", status:"Threatened", threat:"Competitive interactions with introduced Etheostoma edwini may affect the distribution and abundance of E. okaloosae in some areas while in other areas habitat degradation may be more influential in the distributions of the two species; however, available evidence indicates that E. edwini is not negatively affecting E. okaloosae in most areas.", img_url:"https://ecos.fws.gov/docs/species_images/doc4879.jpg", category: fish},
    {common_name:"Nashville Crayfish", scientific_name:"Orconectes shoupi", status:"Endangered ", threat:"There are some concerns for this species due to urban development and stream modifications such as dry-bed retention dams in the Mill Creek drainage.", img_url:"https://www.gannett-cdn.com/-mm-/c9cbf9886e1b3061af19f620347210449c6392c0/c=95-0-1090-747&r=x408&c=540x405/local/-/media/Nashville/2014/06/23/nas-damremoval-02.jpg", category: fish},
    {common_name:"Laurel Dace", scientific_name:"Chrosomus saylori", status:"Endangered ", threat:"Individual populations appear to be healthy but are vulnerable to extirpation by a single event such as a chemical spill; possible threats include siltation due to clearcutting and agricultural practices and the possible construction of a reservoir on Horn Branch.", img_url:"https://clinchchronicle.files.wordpress.com/2014/02/mtnreddace.jpg", category: fish},
    {common_name:"Amber darter", scientific_name:"Percina antesella", status:"Endangered", threat:"Amber Darters are vulnerable to loss of quality habitat resulting from suburban and urban development.", img_url:"http://upload.wikimedia.org/wikipedia/commons/4/43/Percina_antesella01.jpg", category: fish},
    {common_name:"Bluemask darter", scientific_name:"Etheostoma akatulo", status:"Endangered", threat:"Some areas were inundated by the Great Falls Reservoir in the 1910s. The habitat continues to be negatively affected by deterioration of water quality resulting from siltation, pesticides, and other pollutants contributed by coal mining, gravel mining, poor land use practices, and waste discharges.", img_url:"https://mongabay-images.s3.amazonaws.com/15/0406-darter.png", category: fish},
    {common_name:"Boulder darter", scientific_name:"Etheostoma wapiti", status:"Vulnerable", threat:"Vulnerable status is primarily due to restricted distribution and loss of habitat by impoundment.", img_url:"http://www.natgeocreative.com/comp/04/445/1436116.jpg", category: fish},
    {common_name:"Cumberland darter", scientific_name:"Etheostoma susanae", status:"Endangered ", threat:"Habitat loss and modification represent significant threats to the Cumberland darter. Severe degradation from sedimentation, physical habitat disturbance, and contaminants threatens the habitat and water quality on which the Cumberland Darter depends.", img_url:"http://1.bp.blogspot.com/-n1buwtI-1lI/UJfW3sYIKqI/AAAAAAAAADY/aCfpExH7-bM/s1600/Fig-14-wEtheostoma-jimmycarter.jpg", category: fish},
    {common_name:"Conasauga Logperch", scientific_name:"Percina jenkinsi", status:"Critically Endangered", threat:"Potential threats include siltation and agricultural and urban runoff from adjacent developed areas; small range makes this species vulnerable to a single catastrophic event such as a chemical spill.", img_url:"https://upload.wikimedia.org/wikipedia/commons/f/fb/Percina_jenkinsi.jpg", category: fish},
    {common_name:"Chucky Madtom", scientific_name:"Noturus crypticus", status:"Critically Endangered", threat:"Little Chucky Creek drains a highly agricultural watershed, and silt and agricultural chemicals have been implicated in the decline of other madtom species. Sedimentation and water degredation.", img_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Noturus_crypticus_%28Chucky_madtom%29_FWS_13686.jpg/1200px-Noturus_crypticus_%28Chucky_madtom%29_FWS_13686.jpg", category: fish},
    {common_name:"Pygmy madtom", scientific_name:"Noturus stanauli", status:"Endangered", threat:"Habitat and water quality degradation remain the greatest threats to the madtom. The species remains highly vulnerable to extinction from stochastic events", img_url:"https://www.scotcat.com/images/noturus_stanauli.jpg", category: fish},
    {common_name:"Smoky madtom", scientific_name:"Noturus baileyi", status:"Vulnerable", threat:"Threatened by logging activities, road and bridge construction, and mineral exploration. Activities that expose anakeesta shale, which forms sulphuric acid on contact with water, may result in degraded water quality and declines in madtom populations", img_url:"https://www.floridamuseum.ufl.edu/catfish/ictaluridae/26-N_baileyi2.jpg", category: fish},
    {common_name:"American Burying Beetle", scientific_name:"Nicrophorus americanus", status:"Critically Endangered", threat:"Habitat loss, alteration, and degradation, and they now occur over less than 10% of their historic range.", img_url:"https://ecos.fws.gov/docs/species_images/doc5109.jpg", category: insects},
    {common_name:"Karner Blue Butterfly", scientific_name:"Lycaeides melissa samuelis", status:"Endangered", threat:"Habitat loss", img_url:"https://ecos.fws.gov/docs/species_images/doc4905.jpg", category: insects},
    {common_name:"Spruce Fir Spider", scientific_name:"Microhexura montivaga", status:"Threatened", threat:"The widespread death of Fraser fir trees has destroyed many habitats for the spiders, and they were listed as endangered in 1995. Many Fraser firs have died due to infestation with Adelges piceae, the balsam woolly adelgid, an insect pest introduced from Europe.", img_url:"https://upload.wikimedia.org/wikipedia/commons/3/39/Spruce_Fir_Moss_Spider.jpg", category: insects},
    {common_name:"Mitchell's satyr", scientific_name:"Neonympha mitchellii", status:"Endangered", threat:"Habitat Loss and Degradation; Exotic Weed Invasion; Pesticides / Pollutants; Butterfly Collectors", img_url:"https://mnfi.anr.msu.edu/element-images/1763.jpg", category: insects},
    {common_name:"Northeastern beach tiger beetle", scientific_name:"Cicindela dorsalis dorsalis", status:"Threatened", threat:"All populations experience dramatic fluctuations in abundance resulting from natural and human related disturbances. In Maryland, a major threat is increased vegetation growth on the cliffs which results in reduction of the bare areas needed for adult ovipositon and larval development. A related threat at privately owned sites is construction of shoreline erosion control structures that results in cliff stabilization and vegetation growth.  Rising water levels in the Chesapeake and apparent increasing impacts from storms result in cliff erosion and breakdown.", img_url:"https://ecos.fws.gov/docs/species_images/doc4860.jpg", category: insects},
    {common_name:"Puritan Tiger Beetle", scientific_name:"Cicindela puritana", status:"Threatened", threat:"All populations experience dramatic fluctuations in abundance resulting from natural and human related disturbances. In Maryland, a major threat is increased vegetation growth on the cliffs which results in reduction of the bare areas needed for adult ovipositon and larval development. A related threat at privately owned sites is construction of shoreline erosion control structures that results in cliff stabilization and vegetation growth.  Rising water levels in the Chesapeake and apparent increasing impacts from storms result in cliff erosion and breakdown.", img_url:"https://ecos.fws.gov/docs/species_images/doc3366.jpg", category: insects},
    {common_name:"Rusty Patched Bumble Bee", scientific_name:"Bombus affinis", status:"Endangered", threat:"The primary threats attributed to the severe decline of Bombus affinis include pathogen spill-over from commercial to wild bees; habitat loss due to agriculture and development; pesticide use; and climate change. Reduced genetic diversity, which can be a result of declining, isolated subpopulations caused by any of the aforementioned factors, likely also threatens this species.", img_url:"https://ecos.fws.gov/docs/species_images/doc5094.jpg", category: insects},
    {common_name:"Hine's Emerald Dragonfly", scientific_name:"Somatochlora hineana", status:"Threatened", threat:"Extant occurrences are threatened by the following activities: petroleum refineries and other heavy industry, a proposed highway project, quarrying, urban non-point water pollution, and ATV use in Illinois; agricultural non-point water pollution (surface and groundwater) and recreational development in Wisconsin. Most significant threats are habitat/alteration/destruction from development of commercial and residential areas, quarrying, creating landfills, constructing pipelines, and filling of wetlands.", img_url:"http://www.biologicaldiversity.org/assets/img/species/invertebrates/HinesEmeraldDragonfly_PaulBurton.jpg", category: insects},
    {common_name:"Illinois Cave Arthopod", scientific_name:"Gammarus acherondytes", status:"Endangered", threat:"Habitat loss", img_url:"http://oceanexplorer.noaa.gov/explorations/05deepcorals/logs/nov8/media/fig4amphipod_600.jpg", category: insects},
    {common_name:"Dakota Skipper", scientific_name:"Hesperia dacotae", status:"Vulnerable", threat:"Habitat loss", img_url:"https://www.fws.gov/midwest/Endangered/images/insects/dask/FirstDASKMaleRearedMNZooJune2014ByErikRunquist.jpg", category: insects},
    {common_name:"Hungerford's Crawling Water Beetle", scientific_name:"Brychius hungerfordi", status:"Endangered", threat:"Predation", img_url:"https://ecos.fws.gov/docs/species_images/doc4853.jpg", category: insects},
    {common_name:"Bartram's Hairstreak Butterfly", scientific_name:"Strymon acis bartrami", status:"Critically Endangered ", threat:"Threats are high and some are probably not controllable, and predation by exotic ants seems likely to be a severe, pervasive, and uncontrollable threat.", img_url:"https://c1.staticflickr.com/3/2304/2213490904_6927e27d3f_b.jpg", category: insects},
    {common_name:"Florida Leafwing Butterfly", scientific_name:"Anaea troglodyta floridalis", status:"Threatened", threat:"Loss of habitat", img_url:"http://butterfliesofamerica.com/images/Nymphalidae/Charaxinae/Anaea_troglodyta_floridalis/Anaea_troglodyta_floridalis_HOLOTYPE_M_of_Anaea_aidea_floridalis-USA-FLORIDA-Miami-Dade_Co.-Florida_City_10-XII-1936-AMNH-3-sm.jpg", category: insects},
    {common_name:"Miami Blue Butterfly", scientific_name:"Cyclargus (=hemiargus) thomasi bethunebakeri", status:"Endangered", threat:"Loss of habitat", img_url:"https://ecos.fws.gov/docs/species_images/doc5110.jpg", category: insects},
    {common_name:"Gray Wolf", scientific_name:"Canis lupus", status:"Endangered", threat:"Their original worldwide range has been reduced by about one-third, primarily in developed areas of Europe, Asia, Mexico, and the United States by poisoning and deliberate persecution due to depredation on livestock. Since about 1970, legal protection, land-use changes, and rural human population shifts to cities have arrested wolf population declines and fostered natural recolonization in parts of Western Europe and the United States, and reintroduction in the western United States. Continued threats include competition with humans for livestock, especially in developing countries, exaggerated concern by the public concerning the threat and danger of wolves, and fragmentation of habitat, with resulting areas becoming too small for populations with long-term viability.", img_url:"https://ecos.fws.gov/docs/species_images/doc3630.jpg", category: mammals},
    {common_name:"Canada Lynx", scientific_name:"Lynx canadensis", status:"Threatened", threat:"In most of Canada and Alaska, trapping of lynx for the fur trade is managed through regulated seasons. Trapping can reduce lynx populations and can have the greatest impact when hare populations cyclically crash. In the 1980s, in response to concerns about over-harvest during the cyclic low of the lynx-hare cycle, Alaska and most Canadian provinces modifying seasons or bag limits to match harvest with lynx population levels and trends.", img_url:"https://ecos.fws.gov/docs/species_images/doc4979.jpg", category: mammals},
    {common_name:"Gray bat", scientific_name:"Myotis grisescens", status:"Endangered ", threat:"Cave distrubance and deforestation", img_url:"https://ecos.fws.gov/docs/species_images/doc1480.jpg", category: mammals},
    {common_name:"Virginia Northern Flying Squirrel ", scientific_name:"Glaucomys sabrinus", status:"Endangered ", threat:"Habitat destruction has been the primary cause of population decline. ", img_url:"http://www.alleghenyclimate.org/images/wvnfs.jpg", category: mammals},
    {common_name:"Northern long-eared Bat ", scientific_name:"Myotis septentrionalis", status:"Threatened ", threat:"Timber harvesting may interfere with these bats' ability to utilize trees for nursery colonies and day roosts. It also may prove detrimental to their foraging habits in forested areas.", img_url:"https://static.inaturalist.org/photos/6342192/medium.jpg?1487704803", category: mammals},
    {common_name:"Virginia Big Eared Bat", scientific_name:"Corynorhinus (=plecotus) townsendii virginianus", status:"Endangered", threat:"Use of chemical and biological insecticides is another source of concern affecting their food supply. A less vital, yet very real threat to M. septentrionalis is the disturbance they face in the caves (where recreational 'caving' is popular) or mines (which are often closed after being abandoned) where they hibernate.", img_url:"http://www.planet-mammiferes.org/Photos/Volants/Vespert/PlecTow2.jpg", category: mammals},
    {common_name:"Indiana Bat", scientific_name:"Myotis sodalis", status:"Endangered", threat:"A significant threat is human disturbance at winter caves, which causes aroused bats to deplete energy reserves. Handling of hibernating bats by researchers may result in the bats moving to the use of less suitable hibernacula, causing additional loss of fat reserves.", img_url:"https://ecos.fws.gov/docs/species_images/doc4847.jpg", category: mammals},
    {common_name:"West Indian Manatee", scientific_name:"Trichechus manatus", status:"Vulnerable", threat:"About half of adult mortality rangewide is attributable to human-related causes, primarily watercraft collisions. This is significant because the manatee population growth rate is highly sensitive to changes in adult survival rate. The future of the Florida manatee is also jeopardized by the predicted loss and deterioration of warm-water habitat, including retirement or deregulation of aging power plants and reduction in natural spring flows.", img_url:"https://ecos.fws.gov/docs/species_images/doc3661.jpg", category: mammals},
    {common_name:"Fin Whale", scientific_name:"Balaenoptera physalus", status:"Endangered", threat:"Prior to the advent of modern whaling in the late 19th century, Fin Whales were largely immune from human predation because they were too hard to catch. Fin Whales were depleted worldwide by commercial whaling in the 20th century. Fin Whales have been protected in the Southern Hemisphere and North Pacific since 1975, and catches ceased in the North Atlantic by 1990, except for small “aboriginal subsistence” catches off Greenland", img_url:"https://s-media-cache-ak0.pinimg.com/originals/7b/6a/fb/7b6afbddef555919975b869ed0021baf.jpg", category: mammals},
    {common_name:"Red wolf", scientific_name:"Canis rufus", status:"Critically Endangered", threat:"Hybridization with Coyotes or Red Wolf x Coyote hybrids is the primary threat to the species' persistence in the wild. While hybridization with Coyotes was a factor in the Red Wolf's initial demise in the wild, it was not detected as a problem in north-eastern North Carolina until approximately 1992. Indeed, northeastern North Carolina was determined to be ideal for Red Wolf reintroductions because of a purported absence of coyotes.", img_url:"https://ecos.fws.gov/docs/species_images/doc4996.jpg", category: mammals},
    {common_name:"North Atlantic right Whale", scientific_name:"Eubalaena glacialis", status:"Endangered", threat:"Right Whales in the North Atlantic are no longer hunted, and the most serious current threat is death or injury from entanglements in fishing gear and collisions with ships off the eastern coast of North America.", img_url:"https://iucnredlist-photos.s3.amazonaws.com/thumb/1644313283.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1519481999&Signature=%2FI9fvxUw%2BEy%2BcVemWmwlePKEmy0%3D", category: mammals},
    {common_name:"Anastasia Island Beach Mouse", scientific_name:"Peromyscus polionotus phasma", status:"Endangered", threat:"Predation", img_url:"https://ecos.fws.gov/docs/species_images/doc1970.jpg", category: mammals},
    {common_name:"Perdido Key Beach Mouse", scientific_name:"Peromyscus polionotus trissyllepsis", status:"Endangered", threat:"Predation", img_url:"https://ecos.fws.gov/docs/species_images/doc4484.bmp", category: mammals},
    {common_name:"Southeastern Beach Mouse", scientific_name:"Perromyscus pollionotus niveiventris", status:"Threatened", threat:"Predation", img_url:"https://ecos.fws.gov/docs/species_images/doc1971.jpg", category: mammals},
    {common_name:"Florida Panther", scientific_name:"Puma (=felis) concolor coryi", status:"Endangered", threat:"Human Predation and habitat loss", img_url:"https://ecos.fws.gov/docs/species_images/doc3663.jpg", category: mammals},
    {common_name:"Lower Keys Marsh Rabbit", scientific_name:"Sylvilagus palustris hefneri", status:"Endangered", threat:"Predation and habitat loss", img_url:"https://ecos.fws.gov/docs/species_images/doc5036.jpg", category: mammals},
    {common_name:"Key Deer", scientific_name:"Odocoileus virginianus clavium", status:"Endangered", threat:"Today’s threats include habitat degradation, hunting, destruction, and alteration.  Habitat alteration at the hands of urban development has caused a substantial loss in available vegetation and natural resources, as well as causing habitat to become fragmented.", img_url:"https://ecos.fws.gov/docs/species_images/doc4914.jpg", category: mammals},
    {common_name:"Florida Bonneted Bat", scientific_name:"Eumops floridanus", status:"Vulnerable ", threat:"Vulnerable to habitat loss (in urban and forested areas), habitat alteration (removal of old trees with cavities, or buildings with spaces suitable for roosting), and pesticide spraying for mosquitoes.", img_url:"http://all-len-all.com/wp-content/uploads/2014/07/florida-bonneted-bat-wcs-endangered.jpg", category: mammals},
    {common_name:"Plymouth redbelly Turtle", scientific_name:"Pseudemys rubriventris bangsi)", status:"Endangered", threat:"Habitat loss", img_url:"http://www.biologicaldiversity.org/campaigns/esa_works/gallery/images2/NorthernRed-BelliedCooter_JohnWhite_VirginiaHerpetologicalSociety.jpg", category: reptiles},
    {common_name:"Bog Turtle", scientific_name:"Clemmys muhlenbergii", status:"Threatened", threat:"Much Bog Turtle habitat has been destroyed by drainage and conversion in recent centuries as its wetland habitat is generally located in optimal agricultural soils and landscapes, processes that continue to some extent into the present. Being often located at the lower edges of intensively farmed lands, sedimentation and agrochemical run-off into wetland habitat is an issue.", img_url:"https://ecos.fws.gov/docs/species_images/doc4962.jpg", category: reptiles},
    {common_name:"Leatherback Sea Turtle", scientific_name:"Dermochelys coriacea", status:"Critically Endangered", threat:" 1) Fisheries bycatch: incidental capture of marine turtles in fishing gear targeting other species;
    2) Take: direct utilization of turtles or eggs for human use (i.e. consumption, commercial products);
    3) Coastal Development affecting critical turtle habitat: human-induced alteration of coastal environments due to construction, dredging, beach modification, etc.;
    4) Pollution and Pathogens: marine pollution and debris that affect marine turtles (i.e. through ingestion or entanglement, disorientation caused by artificial lights), as well as impacts of pervasive pathogens (e.g. fibropapilloma virus) on turtle health;
    5) Climate change: current and future impacts from climate change on marine turtles and their habitats.", img_url:"https://ecos.fws.gov/docs/species_images/doc3727.jpg", category: reptiles},
    {common_name:"Green Sea Turtle", scientific_name:"Chelonia mydasa", status:"Endangered ", threat:"Hunting, poaching, egg harvesting, boat strikes, pollution, fishermen nets, fibropapillomatosis.", img_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Green_turtle_swimming_over_coral_reefs_in_Kona.jpg/1024px-Green_turtle_swimming_over_coral_reefs_in_Kona.jpg", category: reptiles},
    {common_name:"Bog Turtle", scientific_name:"Glyptemys muhlenbergii", status:"Critically Endangered ", threat:"Invasive Plants, Urban Development, and Black Market pet trade.", img_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Bog_Turtle.jpg/800px-Bog_Turtle.jpg", category: reptiles},
    {common_name:"Cheat Mountain salamander", scientific_name:"Plethodon nettingi", status:"Threatened", threat:"The main threat to this species is habitat loss and degradation due to logging, mining, recreational development, and road construction. Competition with Plethodon cinereous might also be a limiting factor. However, these threats are all minimal and the population is probably stable.", img_url:"https://ecos.fws.gov/docs/species_images/doc1752.jpg", category: reptiles},
    {common_name:"Kemp's Ridley Sea Turtle", scientific_name:"Lepidochelys kempii", status:"Threatened", threat:"Habitat loss", img_url:"https://iucnredlist-photos.s3.amazonaws.com/thumb/787195903.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1519497267&Signature=7UnnHZuyDxAoMIs3My5lc08EcuY%3D", category: reptiles},
    {common_name:"Loggerhead Sea Turtle", scientific_name:"Caretta caretta", status:"Endangered", threat:"Fisheries bycatch: incidental capture of marine turtles in fishing gear targeting other species; Take: direct utilization of turtles or eggs for human use (i.e., consumption, commercial products); Coastal Development affecting critical turtle habitat. Threats to Loggerheads vary in time and space, and in relative impact to populations", img_url:"https://ecos.fws.gov/docs/species_images/doc3723.jpg", category: reptiles},
    {common_name:"Hawksbill Turtle", scientific_name:"Eretmochelys imbricata", status:"Critically Endangered", threat:"Tortoiseshell Trade. Recent and historical tortoiseshell trade statistics are key to understanding the enormous and enduring effect that trade has had on Hawksbill populations around the world . Significant domestic trade in Hawksbill products continues to be a major problem in many countries and, despite international and domestic prohibitions and the lessening of the volume in the last decade, trade remains an ongoing and pervasive threat in the Americas and southeast Asia.", img_url:"https://ecos.fws.gov/docs/species_images/doc4876.jpg", category: reptiles},
    {common_name:"Eastern Indigo Snake", scientific_name:"Drymarchon corais couperi", status:"Threatened", threat:"Decline is attributed to loss of mature longleaf pine habitat (e.g., conversion to slash and sand pine plantation, urbanization, citrus, mining, etc.), commercial collecting for pet trade (now illegal and has declined), and former widespread gassing of tortoise burrows (to collect rattlesnakes).", img_url:"https://ecos.fws.gov/docs/species_images/doc3730.jpg", category: reptiles},
    {common_name:"Massasauga", scientific_name:"Sistrurus catenatus", status:"Threatened ", threat:"Decline has been due to habitat loss and fragmentation caused by agricultural development, urbanization, damming, and drainage of wetlands.", img_url:"https://upload.wikimedia.org/wikipedia/commons/e/e6/Sistrurus-catenatus-edwardsii_CDC-small.jpg", category: reptiles},
    {common_name:"Black Pine Snake", scientific_name:"Pituophis melanoleucus lodingi", status:"Threatened", threat:"Habitat loss", img_url:"http://www.freewebs.com/slitherbriggs/Pituophis%20melanoleucus%20lodingi%20YOUNG%20with%20light%20pattern%20Photo%20by%20Patrick%20Houston%20Briggs%20crtsy%20Rick%20Smith%20prnt%20scn.JPG", category: reptiles},
    {common_name:"Ringed Map turtle", scientific_name:"Graptemys oculifera", status:"Threatened", threat:"Over 21% of the range of Graptemys oculifera had already been channelized by 1986. Plans for channelization of an additional 28% of the Pearl River and over 160 km of the Bogue Chitto river, while not executed, have not been entirely rescinded and remain as a significant potential threat.", img_url:"http://www.louisianaherps.com/_Media/dsc04481_med.jpeg", category: reptiles},
    {common_name:"Gopher tortoise", scientific_name:"Gopherus polyphemus", status:"Vulnerable", threat:"Habitat loss", img_url:"https://upload.wikimedia.org/wikipedia/commons/b/b2/Big_Boy_%28_Gopherus_Polyphemus_from_New_Smyrna_Beach%2C_Florida_%29_-_Flickr_-_Andrea_Westmoreland.jpg", category: reptiles},
    {common_name:"Copperbellied Water Snake", scientific_name:"Nerodia erythrogaster neglecta", status:"Threatened", threat:"Habitat loss", img_url:"http://www.ectotherms.net/gallery/main.php?g2_view=core.DownloadItem&g2_itemId=1173&g2_serialNumber=3", category: reptiles},
    {common_name:"Eastern Indigo Snake", scientific_name:"Drymarchon couperi", status:"Threatened ", threat:"Decline is attributed to loss of mature longleaf pine habitat (e.g., conversion to slash and sand pine plantation, urbanization, citrus, mining, etc.), commercial collecting for pet trade (now illegal and has declined), and former widespread gassing of tortoise burrows (to collect rattlesnakes).", img_url:"http://www.calusaherp.org/Speakers/bill_images/Drymarchon%20corais%20couperi,%20A1,%20Highlands%20Co,%20FL.jpg", category: reptiles},
    {common_name:"Bluetail Mole skink", scientific_name:"Eumeces egregius lividus", status:"Threatened", threat:"Habitat loss is the main threat to the bluetail mole skink.  Xeric habitat has suffered tremendous losses due to agricultural, residential, and commercial development", img_url:"http://farm1.static.flickr.com/689/22604418880_79049e9a42.jpg", category: reptiles},
    {common_name:"Atlantic Salt Marsh snake", scientific_name:"Nerodia clarkii taeniata", status:"Threatened", threat:"Habitat loss and degradation have been the biggest threats to the Atlantic salt marsh snake.  Habitat loss occurs from excessive filling and development in salt marshes.", img_url:"https://www.fws.gov/northflorida/Media/Species/Atl_Salt-Marsh_Snake.jpg", category: reptiles},
    {common_name:"American crocodile", scientific_name:"Crocodylus acutus", status:"Endangered", threat:"This species was hunted and overexploited for its hides in the 1930s until it was protected in the 1970s, however, illegal hunting still occurs. It is also threatened by habitat degradation from coastal development, including destruction of nesting grounds and the destruction of mangrove swamps for shrimp aquaculture.", img_url:"https://ecos.fws.gov/docs/species_images/doc3726.jpg", category: reptiles},
    {common_name:"Culebra Giant Anole", scientific_name:"Anolis roosevelti", status:"Critically Endangered", threat:"The reasons for the species' decline and possible extinction are unknown.", img_url:"http://www.anoleannals.org/wp-content/uploads/2013/11/cuvieri-sleeping-brown-sanchez.jpg", category: reptiles}
])
