MA {common_name:"Plymouth redbelly Turtle", scientific_name:"Pseudemys rubriventris bangsi)", status:"Endangered", threat:"Habitat loss", img_url:"http://www.biologicaldiversity.org/campaigns/esa_works/gallery/images2/NorthernRed-BelliedCooter_JohnWhite_VirginiaHerpetologicalSociety.jpg", category:"reptiles"},

east {common_name:"Bog Turtle", scientific_name:"Clemmys muhlenbergii", status:"Threatened", threat:"Much Bog Turtle habitat has been destroyed by drainage and conversion in recent centuries as its wetland habitat is generally located in optimal agricultural soils and landscapes, processes that continue to some extent into the present. Being often located at the lower edges of intensively farmed lands, sedimentation and agrochemical run-off into wetland habitat is an issue.", img_url:"https://ecos.fws.gov/docs/species_images/doc4962.jpg", category:"reptiles"},
DE {common_name:"Leatherback Sea Turtle", scientific_name:"Dermochelys coriacea", status:"Critically Endangered", threat:"	1) Fisheries bycatch: incidental capture of marine turtles in fishing gear targeting other species;
2) Take: direct utilization of turtles or eggs for human use (i.e. consumption, commercial products);
3) Coastal Development affecting critical turtle habitat: human-induced alteration of coastal environments due to construction, dredging, beach modification, etc.;
4) Pollution and Pathogens: marine pollution and debris that affect marine turtles (i.e. through ingestion or entanglement, disorientation caused by artificial lights), as well as impacts of pervasive pathogens (e.g. fibropapilloma virus) on turtle health;
5) Climate change: current and future impacts from climate change on marine turtles and their habitats.", img_url:"https://ecos.fws.gov/docs/species_images/doc3727.jpg", category:"reptiles"},
MD {common_name:"Green Sea Turtle", scientific_name:"Chelonia mydasa", status:"Endangered ", threat:"Hunting, poaching, egg harvesting, boat strikes, pollution, fishermen nets, fibropapillomatosis.", img_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Green_turtle_swimming_over_coral_reefs_in_Kona.jpg/1024px-Green_turtle_swimming_over_coral_reefs_in_Kona.jpg", category:"reptiles"},
DE {common_name:"Bog Turtle", scientific_name:"Glyptemys muhlenbergii", status:"Critically Endangered ", threat:"Invasive Plants, Urban Development, and Black Market pet trade.", img_url:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Bog_Turtle.jpg/800px-Bog_Turtle.jpg", category:"reptiles"},
WV {common_name:"Cheat Mountain salamander", scientific_name:"Plethodon nettingi", status:"Threatened", threat:"The main threat to this species is habitat loss and degradation due to logging, mining, recreational development, and road construction. Competition with Plethodon cinereous might also be a limiting factor. However, these threats are all minimal and the population is probably stable.", img_url:"https://ecos.fws.gov/docs/species_images/doc1752.jpg", category:"reptiles"},
MD {common_name:"Kemp's Ridley Sea Turtle", scientific_name:"Lepidochelys kempii", status:"Threatened", threat:"Habitat loss", img_url:"https://iucnredlist-photos.s3.amazonaws.com/thumb/787195903.jpg?AWSAccessKeyId=AKIAJIJQNN2N2SMHLZJA&Expires=1519497267&Signature=7UnnHZuyDxAoMIs3My5lc08EcuY%3D", category:"reptiles"},
NC {common_name:"Loggerhead Sea Turtle", scientific_name:"Caretta caretta", status:"Endangered", threat:"Fisheries bycatch: incidental capture of marine turtles in fishing gear targeting other species; Take: direct utilization of turtles or eggs for human use (i.e., consumption, commercial products); Coastal Development affecting critical turtle habitat. Threats to Loggerheads vary in time and space, and in relative impact to populations", img_url:"https://ecos.fws.gov/docs/species_images/doc3723.jpg", category:"reptiles"},
all but N.W. {common_name:"Hawksbill Turtle", scientific_name:"Eretmochelys imbricata", status:"Critically Endangered", threat:"Tortoiseshell Trade. Recent and historical tortoiseshell trade statistics are key to understanding the enormous and enduring effect that trade has had on Hawksbill populations around the world . Significant domestic trade in Hawksbill products continues to be a major problem in many countries and, despite international and domestic prohibitions and the lessening of the volume in the last decade, trade remains an ongoing and pervasive threat in the Americas and southeast Asia.", img_url:"https://ecos.fws.gov/docs/species_images/doc4876.jpg", category:"reptiles"},
GA {common_name:"Eastern Indigo Snake", scientific_name:"Drymarchon corais couperi", status:"Threatened", threat:"Decline is attributed to loss of mature longleaf pine habitat (e.g., conversion to slash and sand pine plantation, urbanization, citrus, mining, etc.), commercial collecting for pet trade (now illegal and has declined), and former widespread gassing of tortoise burrows (to collect rattlesnakes).", img_url:"https://ecos.fws.gov/docs/species_images/doc3730.jpg", category:"reptiles"},
PA {common_name:"Massasauga", scientific_name:"Sistrurus catenatus", status:"Threatened ", threat:"Decline has been due to habitat loss and fragmentation caused by agricultural development, urbanization, damming, and drainage of wetlands.", img_url:"https://upload.wikimedia.org/wikipedia/commons/e/e6/Sistrurus-catenatus-edwardsii_CDC-small.jpg", category:"reptiles"},
S.E. {common_name:"Black Pine Snake", scientific_name:"Pituophis melanoleucus lodingi", status:"Threatened", threat:"Habitat loss", img_url:"http://www.freewebs.com/slitherbriggs/Pituophis%20melanoleucus%20lodingi%20YOUNG%20with%20light%20pattern%20Photo%20by%20Patrick%20Houston%20Briggs%20crtsy%20Rick%20Smith%20prnt%20scn.JPG", category:"reptiles"},
LA/MI {common_name:"Ringed Map turtle", scientific_name:"Graptemys oculifera", status:"Threatened", threat:"Over 21% of the range of Graptemys oculifera had already been channelized by 1986. Plans for channelization of an additional 28% of the Pearl River and over 160 km of the Bogue Chitto river, while not executed, have not been entirely rescinded and remain as a significant potential threat.", img_url:"http://www.louisianaherps.com/_Media/dsc04481_med.jpeg", category:"reptiles"},
GA/FL {common_name:"Gopher tortoise", scientific_name:"Gopherus polyphemus", status:"Vulnerable", threat:"Habitat loss", img_url:"https://upload.wikimedia.org/wikipedia/commons/b/b2/Big_Boy_%28_Gopherus_Polyphemus_from_New_Smyrna_Beach%2C_Florida_%29_-_Flickr_-_Andrea_Westmoreland.jpg", category:"reptiles"},
MI/IN/OH {common_name:"Copperbellied Water Snake", scientific_name:"Nerodia erythrogaster neglecta", status:"Threatened", threat:"Habitat loss", img_url:"http://www.ectotherms.net/gallery/main.php?g2_view=core.DownloadItem&g2_itemId=1173&g2_serialNumber=3", category:"reptiles"},
FL/SC/LA/MI/AL{common_name:"Eastern Indigo Snake", scientific_name:"Drymarchon couperi", status:"Threatened ", threat:"Decline is attributed to loss of mature longleaf pine habitat (e.g., conversion to slash and sand pine plantation, urbanization, citrus, mining, etc.), commercial collecting for pet trade (now illegal and has declined), and former widespread gassing of tortoise burrows (to collect rattlesnakes).", img_url:"http://www.calusaherp.org/Speakers/bill_images/Drymarchon%20corais%20couperi,%20A1,%20Highlands%20Co,%20FL.jpg", category:"reptiles"},
FL {common_name:"Bluetail Mole skink", scientific_name:"Eumeces egregius lividus", status:"Threatened", threat:"Habitat loss is the main threat to the bluetail mole skink.  Xeric habitat has suffered tremendous losses due to agricultural, residential, and commercial development", img_url:"http://farm1.static.flickr.com/689/22604418880_79049e9a42.jpg", category:"reptiles"},
FL {common_name:"Atlantic Salt Marsh snake", scientific_name:"Nerodia clarkii taeniata", status:"Threatened", threat:"Habitat loss and degradation have been the biggest threats to the Atlantic salt marsh snake.  Habitat loss occurs from excessive filling and development in salt marshes.", img_url:"https://www.fws.gov/northflorida/Media/Species/Atl_Salt-Marsh_Snake.jpg", category:"reptiles"},
FL {common_name:"American crocodile", scientific_name:"Crocodylus acutus", status:"Endangered", threat:"This species was hunted and overexploited for its hides in the 1930s until it was protected in the 1970s, however, illegal hunting still occurs. It is also threatened by habitat degradation from coastal development, including destruction of nesting grounds and the destruction of mangrove swamps for shrimp aquaculture.", img_url:"https://ecos.fws.gov/docs/species_images/doc3726.jpg", category:"reptiles"},
PR? {common_name:"Culebra Giant Anole", scientific_name:"Anolis roosevelti", status:"Critically Endangered", threat:"The reasons for the species' decline and possible extinction are unknown.", img_url:"http://www.anoleannals.org/wp-content/uploads/2013/11/cuvieri-sleeping-brown-sanchez.jpg", category:"reptiles"},